frida:
  apk_directory: C:\Users\tarok\OneDrive - purdue.edu\Desktop\Engineering\Year4\semester2\VIP
    chainvisor\Senior Design\ChainRecon\nooie_analysis\The APKs
  device_serial: null
  frida_server_directory: C:\Users\tarok\OneDrive - purdue.edu\Desktop\Engineering\Year4\semester2\VIP
    chainvisor\Senior Design\ChainRecon\third_party\frida
  frida_server_path: null
  preferred_avd: null
network:
  eth_interface: Ethernet
  internet_interface: Wi-Fi
  router_ip: 192.168.123.99
  static_ip: 192.168.123.100/24
  target_ip: 192.168.123.99
scan:
  interface: eth4
  interface_device: \Device\NPF_{DEF}
  interface_name: Wi-Fi
tools:
  apktool: D:\Cyber Security\tools\apktool\apktool.jar
  jadx: D:\Cyber Security\tools\jadx-1.5.5\bin\jadx.bat
