"""Nmap scan parsing and enrichment helpers for ChainRecon."""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from utils.logging_config import get_logger

logger = get_logger("scanner")

try:
    import defusedxml.ElementTree as SafeET  # type: ignore
except ImportError:
    SafeET = None

try:
    import requests  # type: ignore
except ImportError:  # pragma: no cover
    requests = None


class ScannerAnalyzer:
    """Parse and enrich scan results generated by Nmap."""

    # Default mapping — overridden at runtime by config if available.
    _DEFAULT_IOT_PORT_MAP = {
        1883: "MQTT",
        8883: "MQTT over TLS",
        5683: "CoAP",
        5684: "CoAP over DTLS",
        5353: "mDNS",
        1900: "UPnP",
        47808: "BACnet",
    }

    CVE_HINTS = {
        "telnet": "Cleartext remote administration is exposed.",
        "ftp": "Legacy file transfer service may allow weak authentication.",
        "http": "Web administration surface should be reviewed for default credentials and known CVEs.",
        "upnp": "UPnP exposure is commonly associated with misconfiguration risk.",
    }

    def __init__(self, request_get=None, iot_port_map: Optional[Dict[int, str]] = None):
        self.request_get = request_get or (requests.get if requests else None)
        # Allow config-driven IoT port map
        if iot_port_map is not None:
            self.IOT_PORT_MAP = iot_port_map
        else:
            try:
                from utils.config import get_iot_ports
                loaded = get_iot_ports()
                self.IOT_PORT_MAP = loaded if loaded else dict(self._DEFAULT_IOT_PORT_MAP)
            except Exception:
                self.IOT_PORT_MAP = dict(self._DEFAULT_IOT_PORT_MAP)

    def parse_nmap_output(self, file_path: str) -> Dict[str, Any]:
        path = Path(file_path)
        logger.info("Parsing nmap output: %s", path)
        if path.suffix.lower() == ".xml":
            hosts = self._parse_xml(path)
        else:
            hosts = self._parse_text(path.read_text(encoding="utf-8"))

        services = [service for host in hosts for service in host["services"]]
        iot_services = self.identify_iot_services(services)
        cve_hints = self.correlate_cves(services)
        return {
            "metadata": {"source": str(path), "host_count": len(hosts)},
            "findings": {"hosts": hosts, "iot_services": iot_services, "cve_hints": cve_hints},
            "summary": {
                "open_port_count": len(services),
                "iot_service_count": len(iot_services),
                "cve_hint_count": len(cve_hints),
            },
            "risk_indicators": [
                {
                    "severity": "medium",
                    "title": "Potentially risky service exposed",
                    "details": hint["details"],
                }
                for hint in cve_hints
            ],
        }

    def lookup_shodan(self, ip: str, api_key: Optional[str] = None) -> Dict[str, Any]:
        # Prefer env var / config over direct argument
        if not api_key:
            try:
                from utils.config import get_api_key
                api_key = get_api_key("shodan")
            except Exception:
                pass
        if not api_key:
            return {"enabled": False, "ip": ip, "error": "Shodan API key not provided"}
        if self.request_get is None:
            return {"enabled": False, "ip": ip, "error": "requests dependency is not installed"}

        response = self.request_get(
            f"https://api.shodan.io/shodan/host/{ip}",
            params={"key": api_key},
            timeout=10,
        )
        response.raise_for_status()
        payload = response.json()
        return {
            "enabled": True,
            "ip": ip,
            "organization": payload.get("org"),
            "operating_system": payload.get("os"),
            "tags": payload.get("tags", []),
            "ports": payload.get("ports", []),
        }

    def identify_iot_services(self, services: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
        results = []
        for service in services:
            port = int(service.get("port", 0))
            name = (service.get("service") or "").lower()
            protocol_name = self.IOT_PORT_MAP.get(port)
            if protocol_name:
                results.append({"port": port, "service": service.get("service"), "protocol": protocol_name})
            elif any(marker in name for marker in ("mqtt", "coap", "upnp", "mdns", "bacnet")):
                results.append({"port": port, "service": service.get("service"), "protocol": service.get("service")})
        return results

    def correlate_cves(self, services: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
        hints = []
        for service in services:
            service_name = (service.get("service") or "").lower()
            for key, detail in self.CVE_HINTS.items():
                if key in service_name:
                    hints.append({"port": service.get("port"), "service": service.get("service"), "details": detail})
                    break
        return hints

    def _parse_xml(self, path: Path) -> List[Dict[str, Any]]:
        xml_text = path.read_text(encoding="utf-8")
        if SafeET is not None:
            root = SafeET.fromstring(xml_text)
        else:
            # defusedxml is a required dependency; this fallback disables
            # external entities for basic protection if somehow missing.
            parser = ET.XMLParser()
            root = ET.fromstring(xml_text, parser=parser)

        hosts = []
        for host in root.findall("host"):
            address = host.find("address")
            ip_address = address.get("addr") if address is not None else None
            services = []
            for port in host.findall("./ports/port"):
                state = port.find("./state")
                if state is None or state.get("state") != "open":
                    continue
                service = port.find("./service")
                services.append(
                    {
                        "port": int(port.get("portid")),
                        "protocol": port.get("protocol"),
                        "service": service.get("name") if service is not None else None,
                        "product": service.get("product") if service is not None else None,
                        "version": service.get("version") if service is not None else None,
                    }
                )
            hosts.append({"ip": ip_address, "services": services})
        return hosts

    def _parse_text(self, content: str) -> List[Dict[str, Any]]:
        hosts: List[Dict[str, Any]] = []
        current_host: Optional[Dict[str, Any]] = None

        for line in content.splitlines():
            ip_match = re.match(r"Nmap scan report for (?:\S+ \()?([^\s)]+)\)?", line)
            if ip_match:
                current_host = {"ip": ip_match.group(1), "services": []}
                hosts.append(current_host)
                continue

            port_match = re.match(r"(\d+)/(tcp|udp)\s+open\s+([\w\-\/]+)", line.strip())
            if port_match:
                if current_host is None:
                    current_host = {"ip": None, "services": []}
                    hosts.append(current_host)
                current_host["services"].append(
                    {
                        "port": int(port_match.group(1)),
                        "protocol": port_match.group(2),
                        "service": port_match.group(3),
                        "product": None,
                        "version": None,
                    }
                )

        if not hosts:
            hosts.append({"ip": None, "services": []})
        return hosts
