"""Nmap scan parsing and enrichment helpers for ChainRecon."""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional
from urllib.parse import unquote, urlparse
from urllib.request import url2pathname

from utils.logging_config import get_logger

logger = get_logger("scanner")

try:
    import defusedxml.ElementTree as SafeET  # type: ignore
except ImportError:
    SafeET = None

try:
    import requests  # type: ignore
except ImportError:  # pragma: no cover
    requests = None


class ScannerAnalyzer:
    """Parse and enrich scan results generated by Nmap."""

    # Default mapping -- overridden at runtime by config if available.
    _DEFAULT_IOT_PORT_MAP = {
        1883: "MQTT",
        8883: "MQTT over TLS",
        5683: "CoAP",
        5684: "CoAP over DTLS",
        5353: "mDNS",
        1900: "UPnP",
        47808: "BACnet",
    }

    CVE_HINTS = {
        "telnet": "Cleartext remote administration is exposed.",
        "ftp": "Legacy file transfer service may allow weak authentication.",
        "http": "Web administration surface should be reviewed for default credentials and known CVEs.",
        "upnp": "UPnP exposure is commonly associated with misconfiguration risk.",
    }

    def __init__(self, request_get=None, iot_port_map: Optional[Dict[int, str]] = None):
        self.request_get = request_get or (requests.get if requests else None)
        # Allow config-driven IoT port map
        if iot_port_map is not None:
            self.IOT_PORT_MAP = iot_port_map
        else:
            try:
                from utils.config import get_iot_ports
                loaded = get_iot_ports()
                self.IOT_PORT_MAP = loaded if loaded else dict(self._DEFAULT_IOT_PORT_MAP)
            except Exception:
                self.IOT_PORT_MAP = dict(self._DEFAULT_IOT_PORT_MAP)

    def parse_nmap_output(self, file_path: str) -> Dict[str, Any]:
        path = _normalize_file_path(file_path)
        logger.info("Parsing nmap output: %s", path)
        if path.suffix.lower() == ".xml":
            hosts = self._parse_xml(path)
        else:
            hosts = self._parse_text(path.read_text(encoding="utf-8", errors="replace"))

        services = [service for host in hosts for service in host["services"]]
        iot_services = self.identify_iot_services(services)
        cve_hints = self.correlate_cves(services)
        ports = [port for host in hosts for port in host.get("ports", [])]
        state_summary = _combine_state_summaries(hosts)
        return {
            "metadata": {"source": str(path), "host_count": len(hosts)},
            "findings": {"hosts": hosts, "iot_services": iot_services, "cve_hints": cve_hints},
            "summary": {
                "open_port_count": len(services),
                "closed_port_count": _state_count(ports, state_summary, "closed"),
                "filtered_port_count": _state_count(ports, state_summary, "filtered"),
                "scanned_port_count": len(ports) + sum(state_summary.values()),
                "host_up_count": sum(1 for host in hosts if host.get("host_state") == "up"),
                "host_down_count": sum(1 for host in hosts if host.get("host_state") == "down"),
                "iot_service_count": len(iot_services),
                "cve_hint_count": len(cve_hints),
            },
            "risk_indicators": [
                {
                    "severity": "medium",
                    "title": "Potentially risky service exposed",
                    "details": hint["details"],
                }
                for hint in cve_hints
            ],
        }

    def lookup_shodan(self, ip: str, api_key: Optional[str] = None) -> Dict[str, Any]:
        # Prefer env var / config over direct argument
        if not api_key:
            try:
                from utils.config import get_api_key
                api_key = get_api_key("shodan")
            except Exception:
                pass
        if not api_key:
            return {"enabled": False, "ip": ip, "error": "Shodan API key not provided"}
        if self.request_get is None:
            return {"enabled": False, "ip": ip, "error": "requests dependency is not installed"}

        response = self.request_get(
            f"https://api.shodan.io/shodan/host/{ip}",
            params={"key": api_key},
            timeout=10,
        )
        response.raise_for_status()
        payload = response.json()
        return {
            "enabled": True,
            "ip": ip,
            "organization": payload.get("org"),
            "operating_system": payload.get("os"),
            "tags": payload.get("tags", []),
            "ports": payload.get("ports", []),
        }

    def identify_iot_services(self, services: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
        results = []
        for service in services:
            port = int(service.get("port", 0))
            name = (service.get("service") or "").lower()
            protocol_name = self.IOT_PORT_MAP.get(port)
            if protocol_name:
                results.append({"port": port, "service": service.get("service"), "protocol": protocol_name})
            elif any(marker in name for marker in ("mqtt", "coap", "upnp", "mdns", "bacnet")):
                results.append({"port": port, "service": service.get("service"), "protocol": service.get("service")})
        return results

    def correlate_cves(self, services: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
        hints = []
        for service in services:
            service_name = (service.get("service") or "").lower()
            for key, detail in self.CVE_HINTS.items():
                if key in service_name:
                    hints.append({"port": service.get("port"), "service": service.get("service"), "details": detail})
                    break
        return hints

    def _parse_xml(self, path: Path) -> List[Dict[str, Any]]:
        xml_text = path.read_text(encoding="utf-8", errors="replace")
        if SafeET is not None:
            root = SafeET.fromstring(xml_text)
        else:
            # defusedxml is a required dependency; this fallback disables
            # external entities for basic protection if somehow missing.
            parser = ET.XMLParser()
            root = ET.fromstring(xml_text, parser=parser)

        hosts = []
        for host in root.findall("host"):
            address = host.find("address")
            ip_address = address.get("addr") if address is not None else None
            status = host.find("status")
            host_state = status.get("state") if status is not None else None
            services = []
            ports = []
            state_summary: Dict[str, int] = {}
            for port in host.findall("./ports/port"):
                state = port.find("./state")
                state_name = state.get("state") if state is not None else None
                service = port.find("./service")
                parsed = {
                    "port": int(port.get("portid")),
                    "protocol": port.get("protocol"),
                    "state": state_name,
                    "service": service.get("name") if service is not None else None,
                    "product": service.get("product") if service is not None else None,
                    "version": service.get("version") if service is not None else None,
                }
                ports.append(parsed)
                if state_name == "open":
                    services.append({k: v for k, v in parsed.items() if k != "state"})
            for extra_ports in host.findall("./ports/extraports"):
                state_name = extra_ports.get("state")
                count = _safe_int(extra_ports.get("count"))
                if state_name and count:
                    state_summary[state_name] = state_summary.get(state_name, 0) + count
            hosts.append({
                "ip": ip_address,
                "host_state": host_state,
                "ports": ports,
                "services": services,
                "state_summary": state_summary,
            })
        return hosts

    def _parse_text(self, content: str) -> List[Dict[str, Any]]:
        hosts: List[Dict[str, Any]] = []
        current_host: Optional[Dict[str, Any]] = None

        for line in content.splitlines():
            ip_match = re.match(r"Nmap scan report for (?:\S+ \()?([^\s)]+)\)?", line)
            if ip_match:
                current_host = {"ip": ip_match.group(1), "host_state": None, "ports": [], "services": [], "notes": []}
                hosts.append(current_host)
                continue

            if current_host is not None:
                if "Host is up" in line:
                    current_host["host_state"] = "up"
                    continue
                if "Host seems down" in line or "Host is down" in line:
                    current_host["host_state"] = "down"
                    continue
                if line.startswith("Not shown:") or "scanned ports" in line:
                    stripped = line.strip()
                    current_host.setdefault("notes", []).append(stripped)
                    _add_text_state_summary(current_host, stripped)
                    continue

            port_match = re.match(r"(\d+)/(tcp|udp)\s+(\S+)\s+([\w\-\/]+)?", line.strip())
            if port_match:
                if current_host is None:
                    current_host = {"ip": None, "host_state": None, "ports": [], "services": [], "notes": []}
                    hosts.append(current_host)
                parsed = {
                    "port": int(port_match.group(1)),
                    "protocol": port_match.group(2),
                    "state": port_match.group(3),
                    "service": port_match.group(4) or None,
                    "product": None,
                    "version": None,
                }
                current_host["ports"].append(parsed)
                if parsed["state"] == "open":
                    current_host["services"].append({k: v for k, v in parsed.items() if k != "state"})

        if not hosts:
            hosts.append({"ip": None, "host_state": None, "ports": [], "services": [], "notes": []})
        return hosts


def _safe_int(value: Optional[str]) -> int:
    try:
        return int(value) if value is not None else 0
    except (TypeError, ValueError):
        return 0


def _add_text_state_summary(host: Dict[str, Any], line: str) -> None:
    match = re.match(r"Not shown:\s+(\d+)\s+([A-Za-z|_-]+)", line)
    if not match:
        return
    count = int(match.group(1))
    state = match.group(2).lower()
    summary = host.setdefault("state_summary", {})
    summary[state] = summary.get(state, 0) + count


def _combine_state_summaries(hosts: Iterable[Dict[str, Any]]) -> Dict[str, int]:
    combined: Dict[str, int] = {}
    for host in hosts:
        for state, count in host.get("state_summary", {}).items():
            combined[state] = combined.get(state, 0) + int(count)
    return combined


def _state_count(ports: Iterable[Dict[str, Any]], state_summary: Dict[str, int], state: str) -> int:
    explicit = sum(1 for port in ports if port.get("state") == state)
    summarized = sum(count for key, count in state_summary.items() if state in key.split("|"))
    return explicit + summarized


def _normalize_file_path(file_path: str) -> Path:
    raw = file_path.strip().strip('"\'')
    if raw.lower().startswith("file:"):
        parsed = urlparse(raw)
        path = unquote(parsed.path or "")
        if parsed.netloc:
            path = f"//{parsed.netloc}{path}"
        raw = url2pathname(path)
    return Path(raw)
